const student = [
  {
    reg_no: "2101131",
    name: "Langesh",
    department: "CSE",
    year: "II",
    purpose: "Coin Registery Project",
    in_time: "04:37",
    out_time: "5:00",
    date: "22-12-2022",
    status: "Going",
  },
  {
    reg_no: "1901053",
    name: "Harsshanth S",
    department: "CSE",
    year: "4",
    purpose: "Coin Registery Project",
    in_time: "08:14",
    out_time: "4:30",
    date: "23-12-2022",
    status: "Going",
  },
  {
    reg_no: "1901060",
    name: "Karnika Sivani U",
    department: "CSE",
    year: "4",
    purpose: "Atcam project",
    in_time: "09:02",
    out_time: "4:30",
    date: "23-12-2022",
    status: "Going",
  },
  {
    reg_no: "1904061",
    name: "Jayant V",
    department: "MECH",
    year: "4",
    purpose: "Atcam project",
    in_time: "09:02",
    out_time: "4:30",
    date: "23-12-2022",
    status: "Going",
  },
  {
    reg_no: "2005126",
    name: "Santhosh kumar D",
    department: "IT",
    year: "3",
    purpose: "3D printing ",
    in_time: "09:04",
    out_time: "4.40",
    date: "23-12-2022",
    status: "Ongoing",
  },
  {
    reg_no: "2005126",
    name: "Santhosh kumar D",
    department: "IT",
    year: "3",
    purpose: "NBA Project Presentation",
    in_time: "09:04",
    out_time: "4:30",
    date: "23-12-2022",
    status: "Ongoing",
  },
  {
    reg_no: "2005126",
    name: "Santhosh kumar D",
    department: "IT",
    year: "3",
    purpose: "NBA project presentation ",
    in_time: "09:05",
    out_time: "4.30",
    date: "23-12-2022",
    status: "Ongoing ",
  },
];

module.exports = { studentRecords: student };
